### ISSUE TITLE
[emoticones] Inversion d'émoticônes

### ISSUE THREAD

**Issue by entwanne** [zestedesavoir/documents-communication#2]
Bonjour,

En regardant le tableau, je remarque que certaines émoticônes ont peut-être été inversées, en comparaison avec la colonne « Classique ».
Je pense à `:D` qui serait inversé avec `:lol:` (la version classique de `:D` n'étant pas animée, c'est celle de `:lol` qui l'est), et `:colere:` inversé avec `:colere2:` (pour la même raison, `:colere:` est animé en version classique).

**Comment by lypwig** [comment]
Merci, c'est corrigé.
